"""Build a Postman Collection v2.1 JSON file from validated test cases, mirroring
the pytest artifacts generated by ``generators/pytest_generator.py``.

No UI code lives here.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from config import settings
from generators.pytest_generator import (
    EXPIRED_AUTH_HINTS,
    MISSING_AUTH_HINTS,
    NEGATIVE_ID_HINTS,
    SQL_INJECTION_PAYLOAD,
    SQLI_HINTS,
    sample_value_for_type,
)
from llm.llm_generator import TestCase
from parser.openapi_parser import Endpoint
from utils.helpers import get_logger, safe_filename, write_json

logger = get_logger(__name__)

COLLECTION_SCHEMA = "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"


def _resolve_param_value_for_postman(param, test_case: TestCase) -> object:
    text = f"{test_case.title} {test_case.description}".lower()
    if test_case.category == "Security" and any(hint in text for hint in SQLI_HINTS):
        return SQL_INJECTION_PAYLOAD
    if param.location == "path" and test_case.category == "Negative" and any(hint in text for hint in NEGATIVE_ID_HINTS):
        return 999999999 if param.schema_type == "integer" else "invalid-id"
    return sample_value_for_type(param)


def _build_headers(endpoint: Endpoint, test_case: TestCase) -> list[dict[str, str]]:
    text = f"{test_case.title} {test_case.description}".lower()
    if not endpoint.auth:
        return []
    if any(hint in text for hint in MISSING_AUTH_HINTS):
        return []
    if any(hint in text for hint in EXPIRED_AUTH_HINTS):
        return [{"key": "Authorization", "value": "Bearer expired.invalid.token", "type": "text"}]
    return [{"key": "Authorization", "value": "Bearer {{auth_token}}", "type": "text"}]


def _build_url(endpoint: Endpoint, test_case: TestCase) -> dict[str, Any]:
    path_params = {p.name: _resolve_param_value_for_postman(p, test_case) for p in endpoint.parameters if p.location == "path"}
    query_params = {p.name: _resolve_param_value_for_postman(p, test_case) for p in endpoint.parameters if p.location == "query"}

    resolved_path = endpoint.path
    for name, value in path_params.items():
        resolved_path = resolved_path.replace(f"{{{name}}}", str(value))

    path_segments = [segment for segment in resolved_path.split("/") if segment]
    query = [{"key": key, "value": str(value)} for key, value in query_params.items()]

    return {
        "raw": "{{base_url}}" + resolved_path + (("?" + "&".join(f"{q['key']}={q['value']}" for q in query)) if query else ""),
        "host": ["{{base_url}}"],
        "path": path_segments,
        "query": query,
    }


def _build_test_script(test_case: TestCase) -> list[str]:
    lines = [
        f"pm.test(\"{test_case.title} - status code\", function () {{",
        f"    pm.response.to.have.status({test_case.expected_status});",
        "});",
    ]
    if isinstance(test_case.expected_response, dict):
        for field in test_case.expected_response.keys():
            lines.append(f"pm.test(\"{test_case.title} - has field {field}\", function () {{")
            lines.append("    const body = pm.response.json();")
            lines.append(f"    pm.expect(body).to.have.property(\"{field}\");")
            lines.append("});")
    for note in test_case.assertions:
        lines.append(f"// Manual assertion (from generated test case): {note}")
    return lines


def _build_item(endpoint: Endpoint, test_case: TestCase) -> dict[str, Any]:
    return {
        "name": test_case.title,
        "request": {
            "method": endpoint.method,
            "header": _build_headers(endpoint, test_case),
            "url": _build_url(endpoint, test_case),
            "description": test_case.description,
        },
        "response": [],
        "event": [
            {
                "listen": "test",
                "script": {"type": "text/javascript", "exec": _build_test_script(test_case)},
            }
        ],
    }


def build_collection(
    collection_name: str,
    base_url: str,
    endpoint_test_cases: list[tuple[Endpoint, list[TestCase]]],
) -> dict[str, Any]:
    """Build the full Postman Collection v2.1 document.

    Args:
        collection_name: Name shown in Postman for this collection.
        base_url: API base URL, exposed as the ``base_url`` collection variable.
        endpoint_test_cases: Pairs of (endpoint, validated test cases for it).

    Returns:
        A dict matching the Postman Collection v2.1 schema.
    """
    folders: list[dict[str, Any]] = []
    for endpoint, test_cases in endpoint_test_cases:
        if not test_cases:
            continue
        folder_name = f"{endpoint.method} {endpoint.path}"
        items = [_build_item(endpoint, test_case) for test_case in test_cases]
        folders.append({"name": folder_name, "item": items})

    return {
        "info": {
            "name": collection_name,
            "schema": COLLECTION_SCHEMA,
        },
        "item": folders,
        "variable": [
            {"key": "base_url", "value": base_url or ""},
            {"key": "auth_token", "value": ""},
        ],
    }


def generate_postman_collection(
    collection_name: str,
    base_url: str,
    endpoint_test_cases: list[tuple[Endpoint, list[TestCase]]],
    output_path: Path | None = None,
) -> Path:
    """Build and write the Postman collection JSON file.

    Args:
        collection_name: Name shown in Postman for this collection.
        base_url: API base URL.
        endpoint_test_cases: Pairs of (endpoint, validated test cases for it).
        output_path: File to write (defaults to
            ``settings.generated_postman_dir / "collection.json"``).

    Returns:
        The path of the written collection file.
    """
    output_path = output_path or (settings.generated_postman_dir / "collection.json")
    collection = build_collection(collection_name, base_url, endpoint_test_cases)
    write_json(output_path, collection)
    logger.info("Generated Postman collection: %s", output_path)
    return output_path
